-- =====================================================
-- V4: Create tariffs_raw table and load CSV data
-- This table stores the raw tariff data from tariff_database_2025_utf8.csv
-- =====================================================

-- Create tariffs_raw table to store the raw CSV data
CREATE TABLE IF NOT EXISTS tariff.tariffs_raw (
    id BIGSERIAL PRIMARY KEY,
    hts8 VARCHAR(8),
    brief_description TEXT,
    quantity_1_code VARCHAR(10),
    quantity_2_code VARCHAR(10),
    wto_binding_code VARCHAR(1),
    mfn_text_rate TEXT,
    mfn_rate_type_code VARCHAR(10),
    mfn_ave decimal(18,6),
    mfn_ad_val_rate decimal(18,6),
    mfn_specific_rate decimal(18,6),
    mfn_other_rate decimal(18,6),
    col1_special_text TEXT,
    col1_special_mod VARCHAR(50),
    gsp_indicator VARCHAR(10),
    gsp_ctry_excluded TEXT,
    apta_indicator VARCHAR(10),
    civil_air_indicator VARCHAR(10),
    nafta_canada_ind VARCHAR(10),
    nafta_mexico_ind VARCHAR(10),
    mexico_rate_type_code VARCHAR(10),
    mexico_ad_val_rate decimal(18,6),
    mexico_specific_rate decimal(18,6),
    cbi_indicator VARCHAR(10),
    cbi_ad_val_rate decimal(18,6),
    cbi_specific_rate decimal(18,6),
    agoa_indicator VARCHAR(10),
    cbtpa_indicator VARCHAR(10),
    cbtpa_rate_type_code VARCHAR(10),
    cbtpa_ad_val_rate decimal(18,6),
    cbtpa_specific_rate decimal(18,6),
    israel_fta_indicator VARCHAR(10),
    atpa_indicator VARCHAR(10),
    atpa_ad_val_rate decimal(18,6),
    atpa_specific_rate decimal(18,6),
    atpdea_indicator VARCHAR(10),
    jordan_indicator VARCHAR(10),
    jordan_rate_type_code VARCHAR(10),
    jordan_ad_val_rate decimal(18,6),
    jordan_specific_rate decimal(18,6),
    jordan_other_rate decimal(18,6),
    singapore_indicator VARCHAR(10),
    singapore_rate_type_code VARCHAR(10),
    singapore_ad_val_rate decimal(18,6),
    singapore_specific_rate decimal(18,6),
    singapore_other_rate decimal(18,6),
    chile_indicator VARCHAR(10),
    chile_rate_type_code VARCHAR(10),
    chile_ad_val_rate decimal(18,6),
    chile_specific_rate decimal(18,6),
    chile_other_rate decimal(18,6),
    morocco_indicator VARCHAR(10),
    morocco_rate_type_code VARCHAR(10),
    morocco_ad_val_rate decimal(18,6),
    morocco_specific_rate decimal(18,6),
    morocco_other_rate decimal(18,6),
    australia_indicator VARCHAR(10),
    australia_rate_type_code VARCHAR(10),
    australia_ad_val_rate decimal(18,6),
    australia_specific_rate decimal(18,6),
    australia_other_rate decimal(18,6),
    bahrain_indicator VARCHAR(10),
    bahrain_rate_type_code VARCHAR(10),
    bahrain_ad_val_rate decimal(18,6),
    bahrain_specific_rate decimal(18,6),
    bahrain_other_rate decimal(18,6),
    dr_cafta_indicator VARCHAR(10),
    dr_cafta_rate_type_code VARCHAR(10),
    dr_cafta_ad_val_rate decimal(18,6),
    dr_cafta_specific_rate decimal(18,6),
    dr_cafta_other_rate decimal(18,6),
    dr_cafta_plus_indicator VARCHAR(10),
    dr_cafta_plus_rate_type_code VARCHAR(10),
    dr_cafta_plus_ad_val_rate decimal(18,6),
    dr_cafta_plus_specific_rate decimal(18,6),
    dr_cafta_plus_other_rate decimal(18,6),
    oman_indicator VARCHAR(10),
    oman_rate_type_code VARCHAR(10),
    oman_ad_val_rate decimal(18,6),
    oman_specific_rate decimal(18,6),
    oman_other_rate decimal(18,6),
    peru_indicator VARCHAR(10),
    peru_rate_type_code VARCHAR(10),
    peru_ad_val_rate decimal(18,6),
    peru_specific_rate decimal(18,6),
    peru_other_rate decimal(18,6),
    pharmaceutical_ind VARCHAR(10),
    dyes_indicator VARCHAR(10),
    col2_text_rate TEXT,
    col2_rate_type_code VARCHAR(10),
    col2_ad_val_rate DECIMAL(18,6),
    col2_specific_rate decimal(18,6),
    col2_other_rate decimal(18,6),
    begin_effect_date VARCHAR(20),
    end_effective_date VARCHAR(20),
    footnote_comment TEXT,
    additional_duty TEXT,
    korea_indicator VARCHAR(10),
    korea_rate_type_code VARCHAR(10),
    korea_ad_val_rate decimal(18,6),
    korea_specific_rate decimal(18,6),
    korea_other_rate decimal(18,6),
    colombia_indicator VARCHAR(10),
    colombia_rate_type_code VARCHAR(10),
    colombia_ad_val_rate decimal(18,6),
    colombia_specific_rate decimal(18,6),
    colombia_other_rate decimal(18,6),
    panama_indicator VARCHAR(10),
    panama_rate_type_code VARCHAR(10),
    panama_ad_val_rate decimal(18,6),
    panama_specific_rate decimal(18,6),
    panama_other_rate decimal(18,6),
    nepal_indicator VARCHAR(10),
    japan_indicator VARCHAR(10),
    japan_rate_type_code VARCHAR(10),
    japan_ad_val_rate decimal(18,6),
    japan_specific_rate decimal(18,6),
    japan_other_rate decimal(18,6),
    usmca_indicator VARCHAR(10),
    usmca_rate_type_code VARCHAR(10),
    usmca_ad_val_rate decimal(18,6),
    usmca_specific_rate decimal(18,6),
    usmca_other_rate decimal(18,6),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on HTS8 for faster lookups
CREATE INDEX IF NOT EXISTS idx_tariffs_raw_hts8 ON tariff.tariffs_raw(hts8);

-- Add comment for documentation
COMMENT ON TABLE tariff.tariffs_raw IS 'Raw tariff data loaded from tariff_database_2025_utf8.csv';
